const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const Product = require('./models/Product');

const products = [
  // CLOTHING
  {
    name: 'Silk Evening Gown',
    description: 'Elegant floor-length silk gown with a deep V-neckline and flowing train. Perfect for galas and formal occasions.',
    price: 1850,
    originalPrice: 2200,
    category: 'clothing',
    subcategory: 'dresses',
    brand: 'Lumière',
    images: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800'],
    stock: 12,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Midnight Black', 'Ivory', 'Champagne'],
    tags: ['gown', 'evening', 'silk', 'formal'],
    rating: 4.8,
    numReviews: 34,
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    material: '100% Pure Silk',
    careInstructions: 'Dry clean only',
  },
  {
    name: 'Cashmere Trench Coat',
    description: 'Double-breasted cashmere trench coat with a belted waist. A timeless investment piece crafted in Italy.',
    price: 3200,
    originalPrice: 3800,
    category: 'clothing',
    subcategory: 'outerwear',
    brand: 'Maison Élite',
    images: ['https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800'],
    stock: 8,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Camel', 'Black', 'Beige'],
    tags: ['coat', 'cashmere', 'trench', 'winter'],
    rating: 4.9,
    numReviews: 21,
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    material: '100% Cashmere',
    careInstructions: 'Dry clean only',
  },
  {
    name: 'Tailored Wool Blazer',
    description: 'Sharply tailored single-breasted blazer in virgin wool. Features satin lining and hand-stitched lapels.',
    price: 980,
    originalPrice: null,
    category: 'clothing',
    subcategory: 'blazers',
    brand: 'Lumière',
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800'],
    stock: 20,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Navy', 'Charcoal', 'Ivory'],
    tags: ['blazer', 'wool', 'tailored', 'office'],
    rating: 4.7,
    numReviews: 18,
    isFeatured: false,
    isNewArrival: true,
    isBestseller: false,
    material: 'Virgin Wool',
    careInstructions: 'Dry clean only',
  },
  {
    name: 'Lace Cocktail Dress',
    description: 'Knee-length cocktail dress in delicate French lace with scalloped hem and illusion neckline.',
    price: 760,
    originalPrice: 950,
    category: 'clothing',
    subcategory: 'dresses',
    brand: 'Belle Époque',
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800'],
    stock: 15,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Blush', 'Black', 'Navy'],
    tags: ['dress', 'lace', 'cocktail', 'party'],
    rating: 4.6,
    numReviews: 29,
    isFeatured: false,
    isNewArrival: true,
    isBestseller: false,
    material: 'French Lace, Silk Lining',
    careInstructions: 'Hand wash cold or dry clean',
  },

  // JEWELLERY
  {
    name: 'Diamond Solitaire Necklace',
    description: 'Stunning 1.2ct round brilliant diamond set in 18k white gold on a delicate chain. GIA certified.',
    price: 8500,
    originalPrice: null,
    category: 'jewellery',
    subcategory: 'necklaces',
    brand: 'Lumière Gems',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800'],
    stock: 5,
    sizes: [],
    colors: ['White Gold'],
    tags: ['diamond', 'necklace', 'solitaire', '18k'],
    rating: 5.0,
    numReviews: 12,
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    material: '18k White Gold, 1.2ct Diamond',
    careInstructions: 'Store in soft pouch, avoid chemicals',
  },
  {
    name: 'Pearl Drop Earrings',
    description: 'South Sea cultured pearl drops suspended from 18k yellow gold hooks. Each pearl 10-11mm, AA+ grade.',
    price: 1250,
    originalPrice: 1500,
    category: 'jewellery',
    subcategory: 'earrings',
    brand: 'Lumière Gems',
    images: ['https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=800'],
    stock: 10,
    sizes: [],
    colors: ['Yellow Gold', 'White Gold'],
    tags: ['pearl', 'earrings', 'gold', 'classic'],
    rating: 4.9,
    numReviews: 27,
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    material: 'South Sea Pearl, 18k Gold',
    careInstructions: 'Wipe with soft damp cloth after wearing',
  },
  {
    name: 'Sapphire Tennis Bracelet',
    description: 'Exquisite bracelet featuring 3.5ct total weight blue sapphires alternating with diamonds in 18k white gold.',
    price: 5200,
    originalPrice: 6000,
    category: 'jewellery',
    subcategory: 'bracelets',
    brand: 'Lumière Gems',
    images: ['https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800'],
    stock: 4,
    sizes: [],
    colors: ['White Gold'],
    tags: ['sapphire', 'bracelet', 'tennis', 'diamonds'],
    rating: 4.8,
    numReviews: 9,
    isFeatured: true,
    isNewArrival: false,
    isBestseller: false,
    material: '18k White Gold, Sapphires, Diamonds',
    careInstructions: 'Professional cleaning recommended annually',
  },
  {
    name: 'Gold Signet Ring',
    description: 'Classic signet ring in solid 18k yellow gold with hand-engraved floral motif. A heirloom-quality piece.',
    price: 980,
    originalPrice: null,
    category: 'jewellery',
    subcategory: 'rings',
    brand: 'Lumière Gems',
    images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800'],
    stock: 14,
    sizes: ['5', '6', '7', '8', '9'],
    colors: ['Yellow Gold', 'Rose Gold'],
    tags: ['ring', 'signet', 'gold', 'engraved'],
    rating: 4.7,
    numReviews: 16,
    isFeatured: false,
    isNewArrival: true,
    isBestseller: false,
    material: '18k Gold',
    careInstructions: 'Polish with gold cloth',
  },

  // COSMETICS
  {
    name: 'Velvet Rouge Lip Collection',
    description: 'Set of 5 long-wearing velvet matte lipsticks in curated luxury shades. Formula enriched with vitamin E and argan oil.',
    price: 185,
    originalPrice: 225,
    category: 'cosmetics',
    subcategory: 'lips',
    brand: 'Lumière Beauty',
    images: ['https://images.unsplash.com/photo-1586495777744-4e6232bf2177?w=800'],
    stock: 40,
    sizes: [],
    colors: ['Ruby Red', 'Nude Beige', 'Rose Pink', 'Berry', 'Coral'],
    tags: ['lipstick', 'matte', 'velvet', 'long-lasting'],
    rating: 4.7,
    numReviews: 56,
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    material: 'Vitamin E, Argan Oil, Pigment Complex',
    careInstructions: 'Keep away from heat and direct sunlight',
  },
  {
    name: 'Caviar Skin Serum',
    description: 'Ultra-luxurious anti-aging serum with caviar extract, 24k gold particles, and hyaluronic acid. Visibly firms and brightens.',
    price: 420,
    originalPrice: null,
    category: 'cosmetics',
    subcategory: 'skincare',
    brand: 'Lumière Beauty',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800'],
    stock: 25,
    sizes: ['30ml', '50ml'],
    colors: [],
    tags: ['serum', 'anti-aging', 'caviar', 'gold'],
    rating: 4.9,
    numReviews: 38,
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    material: 'Caviar Extract, 24k Gold, Hyaluronic Acid',
    careInstructions: 'Apply to clean skin morning and night. SPF recommended during day.',
  },
  {
    name: 'Midnight Orchid Perfume',
    description: 'An intoxicating eau de parfum with top notes of bergamot, heart of black orchid and base of sandalwood and musk. 75ml.',
    price: 295,
    originalPrice: 350,
    category: 'cosmetics',
    subcategory: 'fragrance',
    brand: 'Lumière Beauty',
    images: ['https://images.unsplash.com/photo-1541643600914-78b084683702?w=800'],
    stock: 30,
    sizes: ['50ml', '75ml', '100ml'],
    colors: [],
    tags: ['perfume', 'fragrance', 'orchid', 'luxury'],
    rating: 4.8,
    numReviews: 44,
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    material: 'Bergamot, Black Orchid, Sandalwood, Musk',
    careInstructions: 'Store in cool dry place away from sunlight',
  },
  {
    name: 'Luminous Foundation SPF 30',
    description: 'Buildable coverage foundation with a natural satin finish. Infused with skincare actives for all-day hydration.',
    price: 98,
    originalPrice: null,
    category: 'cosmetics',
    subcategory: 'face',
    brand: 'Lumière Beauty',
    images: ['https://images.unsplash.com/photo-1631214524020-3c69b7803c8d?w=800'],
    stock: 50,
    sizes: ['30ml'],
    colors: ['Porcelain', 'Ivory', 'Sand', 'Beige', 'Caramel', 'Espresso'],
    tags: ['foundation', 'spf', 'luminous', 'hydrating'],
    rating: 4.6,
    numReviews: 72,
    isFeatured: false,
    isNewArrival: true,
    isBestseller: false,
    material: 'Hyaluronic Acid, SPF 30, Vitamin C',
    careInstructions: 'Keep away from heat',
  },

  // ACCESSORIES
  {
    name: 'Crocodile Leather Handbag',
    description: 'Structured top-handle bag in genuine crocodile-embossed leather with gold hardware. Includes dust bag and authenticity card.',
    price: 2800,
    originalPrice: 3200,
    category: 'accessories',
    subcategory: 'handbags',
    brand: 'Maison Élite',
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800'],
    stock: 7,
    sizes: [],
    colors: ['Black', 'Cognac', 'Burgundy'],
    tags: ['handbag', 'leather', 'crocodile', 'luxury'],
    rating: 4.9,
    numReviews: 19,
    isFeatured: true,
    isNewArrival: false,
    isBestseller: true,
    material: 'Crocodile-Embossed Calf Leather, Gold Hardware',
    careInstructions: 'Condition with leather cream, store stuffed in dust bag',
  },
  {
    name: 'Silk Square Scarf',
    description: '90x90cm silk twill scarf featuring an exclusive hand-painted botanical print. Each piece is individually numbered.',
    price: 380,
    originalPrice: null,
    category: 'accessories',
    subcategory: 'scarves',
    brand: 'Lumière',
    images: ['https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800'],
    stock: 18,
    sizes: ['90x90cm'],
    colors: ['Emerald', 'Cobalt', 'Blush', 'Ivory'],
    tags: ['scarf', 'silk', 'twill', 'printed'],
    rating: 4.8,
    numReviews: 31,
    isFeatured: false,
    isNewArrival: true,
    isBestseller: false,
    material: '100% Silk Twill',
    careInstructions: 'Dry clean only',
  },
  {
    name: 'Leather Belt with Gold Buckle',
    description: 'Full-grain calfskin leather belt with a substantial 24k gold-plated buckle. Handcrafted in Florence.',
    price: 420,
    originalPrice: 500,
    category: 'accessories',
    subcategory: 'belts',
    brand: 'Maison Élite',
    images: ['https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800'],
    stock: 22,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Tan', 'Brown'],
    tags: ['belt', 'leather', 'gold', 'handcrafted'],
    rating: 4.7,
    numReviews: 23,
    isFeatured: false,
    isNewArrival: false,
    isBestseller: true,
    material: 'Full-Grain Calfskin, Gold-Plated Buckle',
    careInstructions: 'Condition with leather balm periodically',
  },
  {
    name: 'Oversized Tortoise Sunglasses',
    description: 'Oversized square sunglasses in hand-polished Italian acetate with UV400 polarized lenses. Includes leather case.',
    price: 545,
    originalPrice: null,
    category: 'accessories',
    subcategory: 'eyewear',
    brand: 'Lumière',
    images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800'],
    stock: 16,
    sizes: [],
    colors: ['Tortoise', 'Black', 'Havana'],
    tags: ['sunglasses', 'oversized', 'polarized', 'acetate'],
    rating: 4.6,
    numReviews: 28,
    isFeatured: false,
    isNewArrival: true,
    isBestseller: false,
    material: 'Italian Acetate, Polarized UV400 Lenses',
    careInstructions: 'Clean with microfibre cloth only',
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    await Product.deleteMany({});
    console.log('Cleared existing products');

    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products successfully`);

    await mongoose.disconnect();
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
}

seed();
